[package]
name = "darkcoin-table-defs"
version = "0.1.0"
authors = ["Yongjie Wen <nas3dakc@163.com>"]
edition = "2018"
description = "Table definitions for Darkcoin Ethereum client"
license = "Apache-2.0"

[dependencies]
once_cell = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
